testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -25,74 +25,74 @@ jobs:
         run: |
           az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
 
-      - name: Install Bicep CLI
-        run: az bicep install
+      # - name: Install Bicep CLI
+      #   run: az bicep install
 
-      - name: Generate Resource Group Name
-        id: generate_rg_name
-        run: |
-          echo "Generating a unique resource group name..."
-          TIMESTAMP=$(date +%Y%m%d%H%M%S)
-          COMMON_PART="psltestRes"
-          UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
-          echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
-          echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}" 
+      # - name: Generate Resource Group Name
+      #   id: generate_rg_name
+      #   run: |
+      #     echo "Generating a unique resource group name..."
+      #     TIMESTAMP=$(date +%Y%m%d%H%M%S)
+      #     COMMON_PART="pslautomationRes"
+      #     UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+      #     echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
+      #     echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}" 
       
-      - name: Check and Create Resource Group
-        id: check_create_rg
-        run: |
-          set -e  
-          echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
-          if [ "$rg_exists" = "false" ]; then
-            echo "Resource group does not exist. Creating..."
-            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location eastus2 || { echo "Error creating resource group"; exit 1; }
-          else
-            echo "Resource group already exists."
-          fi
+      # - name: Check and Create Resource Group
+      #   id: check_create_rg
+      #   run: |
+      #     set -e  
+      #     echo "Checking if resource group exists..."
+      #     rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+      #     if [ "$rg_exists" = "false" ]; then
+      #       echo "Resource group does not exist. Creating..."
+      #       az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location eastus2 || { echo "Error creating resource group"; exit 1; }
+      #     else
+      #       echo "Resource group already exists."
+      #     fi
         
-      - name: Create openai service
-        id: openai
-        run: |
-          echo "creating azure open service"
-          az cognitiveservices account create --name myOpenAIResource23 --resource-group ${{ env.RESOURCE_GROUP_NAME }} --kind OpenAI --sku S0 --location eastus --yes
-
-      # - name: Generate Unique Solution Prefix
-      #   id: generate_solution_prefix
+      # - name: Create openai service
+      #   id: openai
       #   run: |
-      #     set -e
-      #     COMMON_PART="pslr"
-      #     TIMESTAMP=$(date +%s)  
-      #     UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
-      #     UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
-      #     echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
-      #     echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
+      #     echo "creating azure open service"
+      #     az cognitiveservices account create --name myOpenAIResource23 --resource-group ${{ env.RESOURCE_GROUP_NAME }} --kind OpenAI --sku S0 --location eastus --yes
 
-      # - name: Deploy Bicep Template
-      #   id: deploy
-      #   run: |
-      #     set -e
-      #     az deployment group create \
-      #       --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
-      #       --template-file ResearchAssistant/Deployment/bicep/main.bicep \
-      #       --parameters solutionPrefix=${{ env.SOLUTION_PREFIX }}
+      # # - name: Generate Unique Solution Prefix
+      # #   id: generate_solution_prefix
+      # #   run: |
+      # #     set -e
+      # #     COMMON_PART="pslr"
+      # #     TIMESTAMP=$(date +%s)  
+      # #     UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
+      # #     UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
+      # #     echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
+      # #     echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
+
+      # # - name: Deploy Bicep Template
+      # #   id: deploy
+      # #   run: |
+      # #     set -e
+      # #     az deployment group create \
+      # #       --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
+      # #       --template-file ResearchAssistant/Deployment/bicep/main.bicep \
+      # #       --parameters solutionPrefix=${{ env.SOLUTION_PREFIX }}
             
-      - name: Delete Bicep Deployment
-        if: success()
-        run: |
-          set -e  
-          echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
-          if [ "$rg_exists" = "true" ]; then
-            echo "Resource group exist. Cleaning..."
-            az group delete \
-                --name ${{ env.RESOURCE_GROUP_NAME }} \
-                --yes \
-                --no-wait
-            echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
-          else
-            echo "Resource group does not exists."
-          fi
+      # - name: Delete Bicep Deployment
+      #   if: success()
+      #   run: |
+      #     set -e  
+      #     echo "Checking if resource group exists..."
+      #     rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+      #     if [ "$rg_exists" = "true" ]; then
+      #       echo "Resource group exist. Cleaning..."
+      #       az group delete \
+      #           --name ${{ env.RESOURCE_GROUP_NAME }} \
+      #           --yes \
+      #           --no-wait
+      #       echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
+      #     else
+      #       echo "Resource group does not exists."
+      #     fi
 
       - name: Purging the Resources
         if: success()
@@ -103,7 +103,7 @@ jobs:
           if [ "$rg_exists" = "true" ]; then
           # Purge specific Cognitive Services resource by ResourceId
             echo "Purging Cognitive Services resource..."
-            Remove-AzResource -ResourceId /subscriptions/{subscriptionID}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/{resourceGroup}/deletedAccounts/{resourceName} -ApiVersion 2021-04-30
+            Remove-AzResource -ResourceId /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/deletedAccounts/myOpenAIResource23 -ApiVersion 2021-04-30
             echo "Cognitive Services resource purged..."
           else
             echo "Resource group does not exists."
