testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -93,7 +93,7 @@ jobs:
         if: success()
         run: |
           set -e 
-          
+          # Define variables
           OPENAI_COMMON_PART="purg02-openai"
           openai_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
           echo "Azure OpenAI: $openai_name"
@@ -102,13 +102,31 @@ jobs:
           multiservice_account_name="${{ env.SOLUTION_PREFIX }}${MULTISERVICE_COMMON_PART}"
           echo "Azure Multi Service Account: $multiservice_account_name"
 
+          # Function to handle errors
+          handle_error() {
+            echo "Error during resource deletion process. Exiting with status code: $1"
+            exit $1
+          }
+
+          # Purge OpenAI resource
           echo "Purging the OpenAI Resource..."
-          az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus2/resourceGroups/myResourceGroup4/deletedAccounts/$openai_name --verbose
-          echo "Purged the OpenAI Resource: $openai_name"
+          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup4/providers/Microsoft.CognitiveServices/accounts/$openai_name --verbose; then
+            echo "Failed to purge OpenAI resource: $openai_name"
+            handle_error 1
+          else
+            echo "Purged the OpenAI Resource: $openai_name"
+          fi
    
+           # Purge MultiService account resource
           echo "Purging the MultiService account Resource..."
-          az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus2/resourceGroups/pslautomationRes20241106113537/deletedAccounts/$multiservice_account_name --verbose
-          echo "Purged the MultiService account Resource: $multiservice_account_name"
+          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup4/providers/Microsoft.CognitiveServices/accounts/$multiservice_account_name --verbose; then
+            echo "Failed to purge MultiService account resource: $multiservice_account_name"
+            handle_error 1
+          else
+            echo "Purged the MultiService account Resource: $multiservice_account_name"
+          fi
+
+          echo "Resource purging completed successfully"
 
       # - name: Send Notification on Failure
       #   if: failure()
