testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -25,57 +25,57 @@ jobs:
         run: |
           az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
 
-      # - name: Install Bicep CLI
-      #   run: az bicep install
+      - name: Install Bicep CLI
+        run: az bicep install
 
-      # - name: Generate Resource Group Name
-      #   id: generate_rg_name
-      #   run: |
-      #     echo "Generating a unique resource group name..."
-      #     TIMESTAMP=$(date +%Y%m%d%H%M%S)
-      #     COMMON_PART="pslautomationRes"
-      #     UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
-      #     echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
-      #     echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}" 
+      - name: Generate Resource Group Name
+        id: generate_rg_name
+        run: |
+          echo "Generating a unique resource group name..."
+          TIMESTAMP=$(date +%Y%m%d%H%M%S)
+          COMMON_PART="pslautomationRes"
+          UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+          echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
+          echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}" 
       
-      # - name: Check and Create Resource Group
-      #   id: check_create_rg
-      #   run: |
-      #     set -e  
-      #     echo "Checking if resource group exists..."
-      #     rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
-      #     if [ "$rg_exists" = "false" ]; then
-      #       echo "Resource group does not exist. Creating..."
-      #       az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location eastus2 || { echo "Error creating resource group"; exit 1; }
-      #     else
-      #       echo "Resource group already exists."
-      #     fi
+      - name: Check and Create Resource Group
+        id: check_create_rg
+        run: |
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "false" ]; then
+            echo "Resource group does not exist. Creating..."
+            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location eastus2 || { echo "Error creating resource group"; exit 1; }
+          else
+            echo "Resource group already exists."
+          fi
         
-      # - name: Create openai service
-      #   id: openai
-      #   run: |
-      #     echo "creating azure open service"
-      #     az cognitiveservices account create --name myOpenAIResource23 --resource-group ${{ env.RESOURCE_GROUP_NAME }} --kind OpenAI --sku S0 --location eastus --yes
+      - name: Create openai service
+        id: openai
+        run: |
+          echo "creating azure open service"
+          az cognitiveservices account create --name myOpenAIResource23 --resource-group ${{ env.RESOURCE_GROUP_NAME }} --kind OpenAI --sku S0 --location eastus --yes
 
-      # # - name: Generate Unique Solution Prefix
-      # #   id: generate_solution_prefix
-      # #   run: |
-      # #     set -e
-      # #     COMMON_PART="pslr"
-      # #     TIMESTAMP=$(date +%s)  
-      # #     UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
-      # #     UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
-      # #     echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
-      # #     echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
+      - name: Generate Unique Solution Prefix
+        id: generate_solution_prefix
+        run: |
+          set -e
+          COMMON_PART="purg"
+          TIMESTAMP=$(date +%s)  
+          UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
+          UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
+          echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
+          echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
 
-      # # - name: Deploy Bicep Template
-      # #   id: deploy
-      # #   run: |
-      # #     set -e
-      # #     az deployment group create \
-      # #       --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
-      # #       --template-file ResearchAssistant/Deployment/bicep/main.bicep \
-      # #       --parameters solutionPrefix=${{ env.SOLUTION_PREFIX }}
+      - name: Deploy Bicep Template
+        id: deploy
+        run: |
+          set -e
+          az deployment group create \
+            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
+            --template-file ResearchAssistant/Deployment/bicep/main.bicep \
+            --parameters solutionPrefix=${{ env.SOLUTION_PREFIX }}
             
       # - name: Delete Bicep Deployment
       #   if: success()
@@ -94,58 +94,41 @@ jobs:
       #       echo "Resource group does not exists."
       #     fi
 
-      - name: Purging open ai Resources
-        if: success()
-        run: |
-          set -e 
+      # - name: Purging the Resources
+      #   if: success()
+      #   run: |
+      #     set -e 
           
-          # OPENAI_COMMON_PART="-openai"
-          # application_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
-          # echo "Azure Open AI: $application_name"
+      #     OPENAI_COMMON_PART="-openai"
+      #     openai_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
+      #     echo "Azure OpenAI: $openai_name"
 
-          # MULTISERVICE_COMMON_PART="-cogser"
-          # application_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
-          # echo "Azure Open AI: $application_name"
+      #     MULTISERVICE_COMMON_PART="-cogser"
+      #     multiservice_account_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
+      #     echo "Azure Multi Service Account: $application_name"
 
-          echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name myResourceGroup4)
-          if [ "$rg_exists" = "true" ]; then
-            echo "Resource group exist. Cleaning..."
-            az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/myResourceGroup4/deletedAccounts/purgeOpenAIResource5 --verbose
-            echo "Resource group deleted...  myResourceGroup3"
-          else
-            echo "Resource group does not exists."
-          fi
+      #     echo "Purging the OpenAI Resource..."
+      #     az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/myResourceGroup4/deletedAccounts/$openai_name --verbose
+      #     echo "Purged the OpenAI Resource: $openai_name"
+   
+      #     echo "Purging the MultiService account Resource..."
+      #     az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/myResourceGroup4/deletedAccounts/$multiservice_account_name --verbose
+      #     echo "Purged the MultiService account Resource: $multiservice_account_name"
+
+      # - name: Send Notification on Failure
+      #   if: failure()
+      #   run: |
+      #     RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
       
-
-      - name: Purging the content Resources
-        if: success()
-        run: |
-          # set -e  
-          echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name myResourceGroup3)
-          if [ "$rg_exists" = "true" ]; then
-            echo "Resource group exist. Cleaning..."
-            az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/myResourceGroup3/deletedAccounts/testmultires --verbose
-            echo "Resource group deleted...  myResourceGroup3"
-          else
-            echo "Resource group does not exists."
-          fi
-
-      - name: Send Notification on Failure
-        if: failure()
-        run: |
-          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      #     # Construct the email body
+      #     EMAIL_BODY=$(cat <<EOF
+      #     {
+      #       "body": "<p>Dear Team,</p><p>We would like to inform you that the Research Assistant Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
+      #     }
+      #     EOF
+      #     )
       
-          # Construct the email body
-          EMAIL_BODY=$(cat <<EOF
-          {
-            "body": "<p>Dear Team,</p><p>We would like to inform you that the Research Assistant Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
-          }
-          EOF
-          )
-      
-          # Send the notification
-          curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
-            -H "Content-Type: application/json" \
-            -d "$EMAIL_BODY" || echo "Failed to send notification"
+      #     # Send the notification
+      #     curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
+      #       -H "Content-Type: application/json" \
+      #       -d "$EMAIL_BODY" || echo "Failed to send notification"
