testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -110,27 +110,25 @@ jobs:
             exit $1
           }
 
-          az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup4/providers/Microsoft.CognitiveServices/accounts/$multiservice_account_name --verbose
-
-          # # Purge OpenAI resource
-          # echo "Purging the OpenAI Resource..."
-          # if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup4/providers/Microsoft.CognitiveServices/accounts/$openai_name --verbose; then
-          #   echo "Failed to purge OpenAI resource: $openai_name"
-          #   handle_error 1
-          # else
-          #   echo "Purged the OpenAI Resource: $openai_name"
-          # fi
+          # Purge OpenAI resource
+          echo "Purging the OpenAI Resource..."
+          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus2/resourceGroups/pslautomationRes20241106113537/deletedAccounts/$openai_name --verbose; then
+            echo "Failed to purge OpenAI resource: $openai_name"
+            handle_error 1
+          else
+            echo "Purged the OpenAI Resource: $openai_name"
+          fi
    
-          #  # Purge MultiService account resource
-          # echo "Purging the MultiService account Resource..."
-          # if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myResourceGroup4/providers/Microsoft.CognitiveServices/accounts/$multiservice_account_name --verbose; then
-          #   echo "Failed to purge MultiService account resource: $multiservice_account_name"
-          #   handle_error 1
-          # else
-          #   echo "Purged the MultiService account Resource: $multiservice_account_name"
-          # fi
+           # Purge MultiService account resource
+          echo "Purging the MultiService account Resource..."
+          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus2/resourceGroups/pslautomationRes20241106113537/deletedAccounts/$multiservice_account_name --verbose; then
+            echo "Failed to purge MultiService account resource: $multiservice_account_name"
+            handle_error 1
+          else
+            echo "Purged the MultiService account Resource: $multiservice_account_name"
+          fi
 
-          # echo "Resource purging completed successfully"
+          echo "Resource purging completed successfully"
 
       # - name: Send Notification on Failure
       #   if: failure()
